name: Deploy to Vercel

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Create Vercel project if not exists
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if ! vercel projects ls --token $VERCEL_TOKEN | grep -q "${{ github.repository }}"; then
            vercel link --yes --token $VERCEL_TOKEN
          fi

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token $VERCEL_TOKEN
