name: Deploy to Vercel

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Create Vercel project if not exists
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          REPO_NAME="${{ github.repository }}"
          TEAM_SCOPE="namu-labs"
          PROJECT_EXISTS=false
          NEXT_PAGE=""

          while true; do
            if [ -z "$NEXT_PAGE" ]; then
              RESPONSE=$(vercel projects ls --scope $TEAM_SCOPE --token $VERCEL_TOKEN --json)
            else
              RESPONSE=$(vercel projects ls --scope $TEAM_SCOPE --token $VERCEL_TOKEN --next $NEXT_PAGE --json)
            fi

            PROJECT_NAMES=$(echo $RESPONSE | jq -r '.projects[].name')
            NEXT_PAGE=$(echo $RESPONSE | jq -r '.pagination.next')

            for PROJECT_NAME in $PROJECT_NAMES; do
              if [ "$PROJECT_NAME" == "$REPO_NAME" ]; then
                PROJECT_EXISTS=true
                break
              fi
            done

            if [ "$PROJECT_EXISTS" == "true" ] || [ "$NEXT_PAGE" == "null" ]; then
              break
            fi
          done

          if [ "$PROJECT_EXISTS" == "false" ]; then
            echo "Creating new Vercel project: $REPO_NAME"
            echo "y" | vercel --scope $TEAM_SCOPE --token $VERCEL_TOKEN --confirm
          else
            echo "Project $REPO_NAME already exists in team $TEAM_SCOPE"
          fi

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --scope namu-labs --token $VERCEL_TOKEN
